# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-05 08:40
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ogblog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2016, 6, 5, 8, 40, 9, 925022, tzinfo=utc)),
        ),
    ]
